#!/bin/bash

# Source the common-vars file
## . gentoo-config

# Use the exported variables

# Example usage of the exported variables
echo "Boot Type: $boot_type"
echo "Boot Filesystem: $boot_fs"
echo "Root Filesystem: $root_fs"
echo "Init System: $init_system"
echo "Locale: $locale"
echo "Timezone: $timezone"
echo "Hostname: $hostname"
echo "Root Password: $root_password"

# Automatically detect latest version of gentoo of preferred init system
GENTOOVER=$(sed 's|/[^/]*$||' <<< head -l 3 <<< $(curl -fsSL https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/latest-stage3-amd64-systemd.txt) | tail -1 )

# Ask if user wants to partition their disk
valid_ans=("yeah" "Yeah" "YEAH" "y" "Y" "yes" "Yes" "YES")
while true; do
    read -p "Do you need to partition your disk?: (Y/N) " partition_question
    if [[ " ${valid_ans[@]} " =~ " ${partition_question} " ]]; then
        cfdisk
	break
    else
        echo "Invalid filesystem. Please choose one of the following: ${valid_fs[@]}"
    fi
done

# Change Directory into mounted root
cd /mnt/gentoo

# Fetch the gentoo stage3 with preferred init system
wget https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/$GENTOOVER/stage3-amd64-systemd-$GENTOOVER.tar.xz
